  
version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/opt/site/index.html
    networks:
      - nginx_multiplex
networks:
  nginx_multiplex:
