  
version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 5050:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/opt/site/index.html
    networks:
      - nginx_multiplex
networks:
  nginx_multiplex:
